import { Action, IResourceItem } from "@refinedev/core";

interface TitleHandlerOptions {
  resource?: IResourceItem;
  action?: Action;
  params?: Record<string, string | undefined>;
  pathname?: string;
  autoGeneratedTitle?: string;
}

const titleHandler = ({
  resource,
  action,
  params,
  pathname,
  autoGeneratedTitle,
}: TitleHandlerOptions): string => {
  const baseTitle = "A.S. Enterprise Admin Panel";

  if (!resource) return baseTitle;
  else if (!action || action === "list") return `${resource.meta!.label} | ${baseTitle}`;
  else return `${resource.meta!.label} - ${action} | ${baseTitle}`;
};

export default titleHandler;
